
import static java.awt.Color.blue;
import static java.awt.Color.green;
import static java.awt.Color.red;
import java.awt.PopupMenu;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Max
 */
public class ventanaprincipal extends javax.swing.JFrame {

    int validado = 0;
    
    public ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        fondo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        b_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        b_rojo = new javax.swing.JMenuItem();
        b_verde = new javax.swing.JMenuItem();
        b_azul = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        b_size1 = new javax.swing.JMenuItem();
        b_size2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        b_cambio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        escritorio.setLayer(fondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        b_salir.setText("Salir");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        jMenu1.add(b_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Colores");

        b_rojo.setText("Rojo");
        b_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rojoActionPerformed(evt);
            }
        });
        jMenu2.add(b_rojo);

        b_verde.setText("Verde");
        b_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_verdeActionPerformed(evt);
            }
        });
        jMenu2.add(b_verde);

        b_azul.setText("Azul");
        b_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_azulActionPerformed(evt);
            }
        });
        jMenu2.add(b_azul);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Tamaños");

        b_size1.setText("Tamaño 1");
        b_size1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_size1ActionPerformed(evt);
            }
        });
        jMenu4.add(b_size1);

        b_size2.setText("Tamaño 2");
        b_size2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_size2ActionPerformed(evt);
            }
        });
        jMenu4.add(b_size2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Opciones");

        b_cambio.setText("Cambio");
        b_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cambioActionPerformed(evt);
            }
        });
        jMenu5.add(b_cambio);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cambioActionPerformed
    login v1 = new login();
   
    this.escritorio.add (v1); 
    v1.setVisible(true);
    }//GEN-LAST:event_b_cambioActionPerformed

    private void b_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_azulActionPerformed
    fondo.setBackground(blue);        
    }//GEN-LAST:event_b_azulActionPerformed

    private void b_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_verdeActionPerformed
    fondo.setBackground(green);   
    }//GEN-LAST:event_b_verdeActionPerformed

    private void b_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rojoActionPerformed
     fondo.setBackground(red);   
    }//GEN-LAST:event_b_rojoActionPerformed

    private void b_size2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_size2ActionPerformed
    this.setSize(800, 600);        // TODO add your handling code here:
    }//GEN-LAST:event_b_size2ActionPerformed

    private void b_size1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_size1ActionPerformed
    this.setSize(1000, 800);        // TODO add your handling code here:
    }//GEN-LAST:event_b_size1ActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
    System.exit(0);       
    }//GEN-LAST:event_b_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem b_azul;
    private javax.swing.JMenuItem b_cambio;
    private javax.swing.JMenuItem b_rojo;
    private javax.swing.JMenuItem b_salir;
    private javax.swing.JMenuItem b_size1;
    private javax.swing.JMenuItem b_size2;
    private javax.swing.JMenuItem b_verde;
    public static javax.swing.JDesktopPane escritorio;
    public static javax.swing.JPanel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
