/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanainterna;

import java.awt.Color;

/**
 *
 * @author Max
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JDesktopPane();
        tapiz = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        B_ventanaInterna1 = new javax.swing.JMenuItem();
        B_ventanainterna2 = new javax.swing.JMenuItem();
        B_ventanacierratodas = new javax.swing.JMenuItem();
        colores = new javax.swing.JMenu();
        b_color_rojo = new javax.swing.JMenuItem();
        b_color_verde = new javax.swing.JMenuItem();
        b_color_azul = new javax.swing.JMenuItem();
        tamaño = new javax.swing.JMenu();
        b_size1 = new javax.swing.JMenuItem();
        b_size2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setName("fondo"); // NOI18N

        tapiz.setAlignmentX(0.0F);
        tapiz.setAlignmentY(0.0F);
        tapiz.setAutoscrolls(true);

        javax.swing.GroupLayout tapizLayout = new javax.swing.GroupLayout(tapiz);
        tapiz.setLayout(tapizLayout);
        tapizLayout.setHorizontalGroup(
            tapizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        tapizLayout.setVerticalGroup(
            tapizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        fondo.setLayer(tapiz, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tapiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tapiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        inicio.setText("Inicio");

        B_ventanaInterna1.setText("Clientes");
        B_ventanaInterna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ventanaInterna1ActionPerformed(evt);
            }
        });
        inicio.add(B_ventanaInterna1);

        B_ventanainterna2.setText("Productos");
        B_ventanainterna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ventanainterna2ActionPerformed(evt);
            }
        });
        inicio.add(B_ventanainterna2);

        B_ventanacierratodas.setText("Salir");
        B_ventanacierratodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ventanacierratodasActionPerformed(evt);
            }
        });
        inicio.add(B_ventanacierratodas);

        jMenuBar2.add(inicio);

        colores.setText("Colores");

        b_color_rojo.setText("Rojo");
        b_color_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_color_rojoActionPerformed(evt);
            }
        });
        colores.add(b_color_rojo);

        b_color_verde.setText("Verde");
        b_color_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_color_verdeActionPerformed(evt);
            }
        });
        colores.add(b_color_verde);

        b_color_azul.setText("Azul");
        b_color_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_color_azulActionPerformed(evt);
            }
        });
        colores.add(b_color_azul);

        jMenuBar2.add(colores);

        tamaño.setText("Tamaño");

        b_size1.setText("800 * 600");
        b_size1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_size1ActionPerformed(evt);
            }
        });
        tamaño.add(b_size1);

        b_size2.setText("1000 * 800");
        b_size2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_size2ActionPerformed(evt);
            }
        });
        tamaño.add(b_size2);

        jMenuBar2.add(tamaño);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(fondo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_ventanaInterna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ventanaInterna1ActionPerformed
       clientes v1 = new clientes();
       formulario.fondo.add(v1);
       v1.setVisible(true);
       
    }//GEN-LAST:event_B_ventanaInterna1ActionPerformed

    private void B_ventanainterna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ventanainterna2ActionPerformed
        productos v2 = new productos();
        formulario.fondo.add(v2);
        v2.setVisible(true);
    }//GEN-LAST:event_B_ventanainterna2ActionPerformed

    private void B_ventanacierratodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ventanacierratodasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_B_ventanacierratodasActionPerformed

    private void b_color_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_color_rojoActionPerformed
       tapiz.setBackground(Color.red);
        
    }//GEN-LAST:event_b_color_rojoActionPerformed

    private void b_color_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_color_verdeActionPerformed
        tapiz.setBackground(Color.green);
    }//GEN-LAST:event_b_color_verdeActionPerformed

    private void b_color_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_color_azulActionPerformed
         tapiz.setBackground(Color.blue); 
    }//GEN-LAST:event_b_color_azulActionPerformed

    private void b_size2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_size2ActionPerformed
        this.setSize(1000, 800);
    }//GEN-LAST:event_b_size2ActionPerformed

    private void b_size1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_size1ActionPerformed
        this.setSize(800, 600);// TODO add your handling code here:
    }//GEN-LAST:event_b_size1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem B_ventanaInterna1;
    private javax.swing.JMenuItem B_ventanacierratodas;
    private javax.swing.JMenuItem B_ventanainterna2;
    private javax.swing.JMenuItem b_color_azul;
    private javax.swing.JMenuItem b_color_rojo;
    private javax.swing.JMenuItem b_color_verde;
    private javax.swing.JMenuItem b_size1;
    private javax.swing.JMenuItem b_size2;
    private javax.swing.JMenu colores;
    public static javax.swing.JDesktopPane fondo;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu tamaño;
    private javax.swing.JPanel tapiz;
    // End of variables declaration//GEN-END:variables

    private static class internal {

        public internal() {
            
        }
    }

 

    
}
